name: Pipeline CI/CD com DevSecOps (Aula 08)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

permissions:
  security-events: write
  actions: read

jobs:
  
  build_and_test:
    name: 1. Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      - name: Verificando o build (se o index.html existe)
        run: |
          echo "Iniciando teste de build..."
          if [ -f "index.html" ]; then
            echo "Sucesso: index.html encontrado. Build OK."
          else
            echo "Erro: index.html não encontrado!"
            exit 1
          fi

  sast_scan:
    name: 2. SAST (Análise Estática com CodeQL)
    needs: build_and_test 
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      - name: Inicializando o CodeQL (Ferramenta SAST)
        uses: github/codeql-action/init@v3
        with:
          languages: javascript 

      - name: Autobuild do CodeQL
        uses: github/codeql-action/autobuild@v3

      - name: Executando a análise SAST
        
        uses: github/codeql-action/analyze@v3

  dast_scan:
    name: 3. DAST (Análise Dinâmica com OWASP ZAP)
    needs: build_and_test 
    runs-on: ubuntu-latest
    
    steps:
      - name: Executando o Scan DAST (OWASP ZAP)
        
        uses: ZAP/action-baseline@v0.11.0
        with:
          target: 'https://pipeline-kiqv.vercel.app'
        
        continue-on-error: true

        # Forçando a atualização do DAST